# Generated by Django 6.0.2 on 2026-02-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question to display to users')),
                ('option_a', models.CharField(help_text='Option A', max_length=200)),
                ('option_b', models.CharField(help_text='Option B', max_length=200)),
                ('option_c', models.CharField(help_text='Option C', max_length=200)),
                ('option_d', models.CharField(help_text='Option D', max_length=200)),
                ('correct_answer', models.CharField(help_text='The correct answer (full text)', max_length=200)),
                ('explanation', models.TextField(help_text='Explanation of the correct answer')),
                ('category', models.CharField(choices=[('HISTORY', 'Rwandan History'), ('GEOGRAPHY', 'Geography'), ('CULTURE', 'Culture & Traditions'), ('ECONOMICS', 'Economics'), ('LANGUAGE', 'Languages')], default='HISTORY', help_text='Question category', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the question was added')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
    ]
