[bastion]
bastion ansible_host=4.221.88.111 ansible_user=rwaka ansible_password=JuniorRwaka1234

[app]
app-vm ansible_host=10.0.2.4 ansible_user=rwaka ansible_password=JuniorRwaka1234

[app:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="sshpass -p JuniorRwaka1234 ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p rwaka@4.221.88.111"'
ansible_become_password=JuniorRwaka1234